common: &common
  adapter: postgresql
  encoding: unicode
  pool: 25
  host: localhost
  port: 5432

development:
  <<: *common
  database: venkman_development

test:
  <<: *common
  database: venkman_test

production:
  <<: *common
  database: venkman_production
